spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.33/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null # 全局设置不返回为 null 的字段
  freemarker:
    template-loader-path: classpath:/templates

    suffix: .ftl


server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx5fa967d0c28bbbd6
  mpAppSecret: 0a641c5bf1beff91fb591fe1a0e73e3c
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://vex4tt.natappfree.cc/sell/pay/notify

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/leiguang/Downloads/
#  file: /Users/leiguang/Downloads/sell.log
#  level:
#    xin.leiguang.sell.LoggerTest: debug
